language: php

php: 7.2

before_install:
    # configure timezone: https://stackoverflow.com/a/27052708/1348344
    - date
    - export TZ=Europe/Prague
    - date

install:
    - composer update

script:
    - vendor/bin/phpunit

    # coding standard run
    - composer check-cs

    # static analysis
    - composer phpstan

    # import useful data
    - bin/console import-user-groups -vvv
    - bin/console search-and-import-php-groups -vvv
    - bin/console import-meetups -vvv

    # generate website to "/output" directory, it will be deployed later in "deploy" + imports groups and meetups
    - vendor/bin/statie generate source -vvv

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

notifications:
    email: false
