language: php

php: 7.2

install:
    - composer update

script:
    - vendor/bin/phpunit --coverage-clover coverage.xml

    # coding standard run
    - composer check-cs

    # static analysis
    - composer phpstan

    # generate website to "/output" directory, it will be deployed later in "deploy" + imports groups and meetups
    - composer generate

after_script:
    # upload coverage.xml file to Coveralls to analyze it
    - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
    - php php-coveralls.phar --verbose

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

notifications:
    email: newer
