language: php

php: 7.2

install:
    - composer update

script:
    - vendor/bin/phpunit  --coverage-clover coverage.xml

    # test that website is generated
    - vendor/bin/statie generate source
    # coding standard run
    - composer check-cs
    # static analysis
    - composer phpstan

after_script:
    # upload coverage.xml file to Coveralls to analyze it
    - |
        if [[ $PHPUNIT_FLAGS != "" ]]; then
            wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar;
            php coveralls.phar --verbose;
        fi

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

notifications:
    email: newer
