language: php

php: 7.2

install:
    - composer update

script:
    # test that website is generated
    - vendor/bin/statie generate source
    # coding standard run
    - vendor/bin/ecs check bin src
    # static analysis
    - vendor/bin/phpstan analyse bin src --level max --configuration phpstan.neon

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

notifications:
    email: newer
