language: php

php: 7.2

install:
    - composer update

script:
    - vendor/bin/phpunit

    # coding standard run
    - composer check-cs

    # static analysis
    - composer phpstan

    # generate website to "/output" directory, it will be deployed later in "deploy" + imports groups and meetups
    - composer generate

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

notifications:
    email: false
