services:
    _defaults:
        autowire: true

    Statie\StatieTwig\:
        resource: '../src'

    # twig setup
    Twig\Loader\ArrayLoader:
    Twig\Environment:
        $options:
            'cache': '%kernel.cache_dir%/twig'
