imports:
    - { resource: 'config.local.yml', ignore_errors: true }
    - { resource: 'services.yml' }

parameters:
    env(MEETUP_TOKEN): '' # completed in CI or config.local.yml

    meetup_com_api_key: '%env(MEETUP_TOKEN)%'
    found_meetups_storage_file: '%kernel.project_dir%/source/_data/generated/found_meetups.yml'
    topics_to_crawl:
        - 'php'
        - 'laravel'
        - 'symfony'
        - 'cakephp'
        - 'php-framework'
        - 'php-application-development'
        - 'symfony2'
        - 'codeigniter'
        - 'zend-framework'
        - 'nette'
        - 'phpunit'
        # skip these groups to get performance - they are probably all already imported
        # - 'drupal'
        # - 'wordpress'
        # - 'magento'
        # - 'prestashop'

    usa_states:
        al: 'Alabama'
        ak: 'Alaska'
        as: 'American Samoa'
        az: 'Arizona'
        ar: 'Arkansas'
        ca: 'California'
        co: 'Colorado'
        ct: 'Connecticut'
        de: 'Delaware'
        dc: 'District Of Columbia'
        fm: 'Federated States Of Micronesia'
        fl: 'Florida'
        ga: 'Georgia'
        gu: 'Guam'
        hi: 'Hawaii'
        id: 'Idaho'
        il: 'Illinois'
        in: 'Indiana'
        ia: 'Iowa'
        ks: 'Kansas'
        ky: 'Kentucky'
        la: 'Louisiana'
        me: 'Maine'
        mh: 'Marshall Islands'
        md: 'Maryland'
        ma: 'Massachusetts'
        mi: 'Michigan'
        mn: 'Minnesota'
        ms: 'Mississippi'
        mo: 'Missouri'
        mt: 'Montana'
        ne: 'Nebraska'
        nv: 'Nevada'
        nh: 'New Hampshire'
        nj: 'New Jersey'
        nm: 'New Mexico'
        ny: 'New York'
        nc: 'North Carolina'
        nd: 'North Dakota'
        mp: 'Northern Mariana Islands'
        oh: 'Ohio'
        ok: 'Oklahoma'
        or: 'Oregon'
        pw: 'Palau'
        pa: 'Pennsylvania'
        pr: 'Puerto Rico'
        ri: 'Rhode Island'
        sc: 'South Carolina'
        sd: 'South Dakota'
        tn: 'Tennessee'
        tx: 'Texas'
        ut: 'Utah'
        vt: 'Vermont'
        vi: 'Virgin Islands'
        va: 'Virginia'
        wa: 'Washington'
        wv: 'West Virginia'
        wi: 'Wisconsin'
        wy: 'Wyoming'

    country_codes_with_no_php_groups:
        - 'aw'
        - 'af'
        - 'ao'
        - 'ai'
        - 'ax'
        - 'ad'
        - 'am'
        - 'as'
        - 'aq'
        - 'tf'
        - 'ag'
        - 'az'
        - 'bi'
        - 'bj'
        - 'bf'
        - 'bh'
        - 'bs'
        - 'ba'
        - 'bl'
        - 'bz'
        - 'bm'
        - 'bb'
        - 'bt'
        - 'bv'
        - 'bw'
        - 'cf'
        - 'cc'
        - 'cd'
        - 'cg'
        - 'ck'
        - 'km'
        - 'cv'
        - 'cu'
        - 'cw'
        - 'cx'
        - 'ky'
        - 'cy'
        - 'dj'
        - 'dm'
        - 'do'
        - 'er'
        - 'eh'
        - 'fj'
        - 'fk'
        - 'fo'
        - 'fm'
        - 'ga'
        - 'gg'
        - 'gi'
        - 'gn'
        - 'gp'
        - 'gm'
        - 'gw'
        - 'gq'
        - 'gd'
        - 'gl'
        - 'gf'
        - 'gu'
        - 'gy'
        - 'hm'
        - 'ht'
        - 'im'
        - 'io'
        - 'iq'
        - 'is'
        - 'je'
        - 'jo'
        - 'kg'
        - 'kh'
        - 'ki'
        - 'kn'
        - 'xk'
        - 'kw'
        - 'la'
        - 'lb'
        - 'lr'
        - 'ly'
        - 'lc'
        - 'li'
        - 'ls'
        - 'mo'
        - 'mf'
        - 'mc'
        - 'mv'
        - 'mh'
        - 'mk'
        - 'ml'
        - 'mm'
        - 'me'
        - 'mn'
        - 'mp'
        - 'mz'
        - 'mr'
        - 'ms'
        - 'mq'
        - 'mw'
        - 'yt'
        - 'na'
        - 'nc'
        - 'ne'
        - 'nf'
        - 'ni'
        - 'nu'
        - 'nr'
        - 'om'
        - 'pa'
        - 'pn'
        - 'pw'
        - 'pg'
        - 'pr'
        - 'kp'
        - 'py'
        - 'ps'
        - 'pf'
        - 'qa'
        - 're'
        - 'rw'
        - 'sd'
        - 'gs'
        - 'sj'
        - 'sb'
        - 'sl'
        - 'sv'
        - 'sm'
        - 'so'
        - 'pm'
        - 'ss'
        - 'st'
        - 'sr'
        - 'sz'
        - 'sx'
        - 'sc'
        - 'sy'
        - 'tc'
        - 'td'
        - 'tg'
        - 'tj'
        - 'tk'
        - 'tm'
        - 'tl'
        - 'to'
        - 'tt'
        - 'tv'
        - 'tz'
        - 'ug'
        - 'um'
        - 'us'
        - 'uz'
        - 'va'
        - 'vc'
        - 'vg'
        - 'vi'
        - 'vu'
        - 'wf'
        - 'ws'
        - 'ye'
        - 'zm'
        - 'zw'
        - 'bq'
        - 'sh'

