parameters:
    user_groups_storage: '%kernel.project_dir%/source/_data/user_groups.yml'
    meetups_storage: '%kernel.project_dir%/source/_data/meetups.yml'
    meetup_api_key: '3862c18323629314e5c596422581378'

services:
    _defaults:
        autowire: true
        bind:
            $userGroupsStorage: '%user_groups_storage%'
            $meetupsStorage: '%meetups_storage%'
            $meetupApiKey: '%meetup_api_key%'

    Fop\:
        resource: '../'

    Symfony\Component\Console\Application:
        public: true

    GuzzleHttp\Client: