paramters:
    user_groups_storage: '%kernel.project_dir%/source/_data/user_groups.yml'
    meetups_storage: '%kernel.project_dir%/source/_data/meetups.yml'

services:
    _defaults:
        autowire: true
        bind:
            $userGroupsStorage: '%user_groups_storage%'
            $meetupsStorage: '%meetup_storage%'

    Fop\:
        resource: '../'

    Symfony\Component\Console\Application:
        public: true