services:
    _defaults:
        autowire: true
        public: true

    Fop\:
        resource: '../'
        exclude: '../{Entity,DependencyInjection/FopKernel.php}'

    Symfony\Component\Console\Application:
        public: true

    Symplify\PackageBuilder\Yaml\ParameterMergingYamlLoader: ~

    GuzzleHttp\Client: ~

    # Symfony\Console
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
