imports:
    - { resource: 'parameters.yaml' }

services:
    _defaults:
        autowire: true
        public: true

    Fop\:
        resource: '../src'
        exclude: '../src/{Entity,DependencyInjection/FopKernel.php,Contract}'

    Symfony\Component\Console\Application:
        public: true

    Symplify\PackageBuilder\Yaml\ParameterMergingYamlLoader: ~

    GuzzleHttp\Client: ~
    Symplify\PackageBuilder\Http\BetterGuzzleClient: ~

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
