imports:
    - { resource: 'config.local.yaml', ignore_errors: true }
    - { resource: 'parameters.yaml' }

services:
    _defaults:
        autowire: true
        public: true

    Fop\:
        resource: '../src'
        exclude: '../src/{Entity,DependencyInjection/FopKernel.php}'

    Symfony\Component\Console\Application:
        public: true

    Symplify\PackageBuilder\Yaml\ParameterMergingYamlLoader: ~

    GuzzleHttp\Client: ~

    # Symfony\Console
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
